### PR TITLE
installable program

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
this pr make it so it is installable with pip

- program.py is moved to deepdanbooru/__main__.py
- redistribution/program.py is moved to deepdanbooru module
- add evaluate image function.
- add compile flag because i got compile warning message, see warning message below
- update doc
- tensorflow installation is split because pypi may not have correct build. i got `illegal instruction` error message because my cpu does not support AVX 
instructions (related https://github.com/tensorflow/tensorflow/issues/17411). it make me install tensorflow build from here https://github.com/bazelbuild/bazelisk/issues/99

compile warning message:

```
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
```

### CODE REVIEW

**Comment by KichangKim** [comment]
Hi. Thanks for contribution. I found that some issue in your pull requests.

1. encoding problem when open README.md
Simply setup.py is failed due to encoding issue. I think it should be changed like this:
```python
# setyp.py:7
with open("README.md", "r", encoding='utf-8') as fh:
```

2. Missing entry_points in setup.py
I tested your code in Windows PC, then after installing package it doesn't generate executable script (in this case, deepdanbooru.exe) in pip scripts folder. Can you add following code to setup.py?
```python
entry_points={
        "console_scripts": [
            "deepdanbooru=deepdanbooru.__main__:main",
        ]
    },
```

3. Duplicated functionality for image evaluation (redistribution)
Actually, I created redistribution folder for redistribution of evalaution only code, before using github. But do not used anymore. (so it will be removed in near future.) Same functionality already exists in deepdanbooru module, as evaluate-project command. It supports both single image and folder contains multiple image files.

**Comment by rachmadaniHaryono** [comment]
> Duplicated functionality for image evaluation (redistribution)

i miss the similarity with that subcommand

looking at it again, evaluate-project subcommand require project structure which explained on readme

is it possible to refactor it so that other program can use it without creating project structure?

we actually require that on this branch https://gitgud.io/koto/hydrus-dd/tree/deepdanbooru-tf

if it is possible, user can just download the model, tag file and estimate image without creating other file

**Comment by KichangKim** [comment]
I'll add general "evaluate" command for evaluate project or specific model and tags.

**Comment by KichangKim** [comment]
I added "evaluate" command by d5482ddb.
It contains all of options for evaluating single or multiple images.

**Comment by rachmadaniHaryono** [comment]
@KichangKim after looking at commit you made, i still need a function with that return Tuple[score: float, tag: str].

**Comment by KichangKim** [comment]
I added deepdanbooru.commands.evaluate_image, which has same signatures to your original commit. bdd06db2eb
It returns iterator of (tag, score).

For directory, it checks by using os.path.isfile(). If it return False, it try to get file paths in directory. It filters only image files (by its extension, png jpg jpeg gif)

**Comment by rachmadaniHaryono** [comment]
thank you @KichangKim. another question

so every model save the width and height value and it may not 299?

```python
    width = model.input_shape[2]
    height = model.input_shape[1]

    image = dd.data.load_image_for_evaluate(
        image_path, width=width, height=height)
```

**Comment by KichangKim** [comment]
Yes. The original resnet model uses 224x224 and current DeepDanbooru model uses 299x299. Latest experimental model uses 512x512 (training now). 
Original implementation depends to project.json for getting image size, but now it can be obtained from tensorflow model directly.

**Comment by rachmadaniHaryono** [comment]
> For directory, it checks by using os.path.isfile(). If it return False, it try to get file paths in directory. It filters only image files (by its extension, png jpg jpeg gif)

yes, but your method here may make different result

```python
target_image_paths = []

for target_path in target_paths:
    if os.path.isfile(target_path):
        target_image_paths.append(target_path)
    else:
        target_image_paths.extend(dd.io.get_image_file_paths_recursive(target_path))
```
assume these are the target
```
temp
temp
- 1.jpg
- 2.jpg
```
first `temp` is an image without extension and second is a folder
based on that code above target_image_paths will be ['temp'] and not ['temp', 'temp/1.jpg', 'temp/2.jpg']

> It filters only image files (by its extension, png jpg jpeg gif)

some image may not have no or wrong extension, so i hope there is documentation or note about that.

**Comment by KichangKim** [comment]
Added --allow-folder and --folder-filters options for controlling above behaviour.

DeepDanbooru will search image files in folder if TARGET_PATHS is folder, only when --allow-folder is eanbled. Also, you can change file searching behaviour by setting --folder-filters. It accepts multiple glob patterns (separated by comma).

All of these changes also added to help text.

> any plan to upload it to pypi?
Yes, but not now.

**Pull request merged**
